version: '2.1'
volumes:
  postgis-data:

services:
    db:
        image: mdillon/postgis:11
        volumes:
          - postgis-data:/var/lib/postgresql
        container_name: pgis-db
        environment:
          # If you need to create multiple database you can add coma separated databases eg gis,    data
          - POSTGRES_DB=gis
          - POSTGRES_USER=docker
          - POSTGRES_PASS=docker
          # - ALLOW_IP_RANGE=0.0.0.0/0
          # Add extensions you need to be enabled by default in the DB. Default are the three   specified below
          - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,ogr_fdw
        ports:
          - 5434:5432
        restart: on-failure
        healthcheck:
          test: "exit 0"
    
    nginx:
      image: nginx
      hostname: nginx
      container_name: pgis-nginx
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/gis.conf
        # - ./nginx.conf:/etc/nginx.conf
      ports:
        - 8080:80
      links:
        - db
